---
- name: Configurar Servidor de Internet Linux
  hosts: all
  become: true

  vars_files:
    - vars/main.yml

  pre_tasks:
    - name: Atualizar apt cache
      package: update_cache=true cache_valid_time=3600

  roles:
    - gateway
    - squid
